version: '3.9'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v3.0.9
    container_name: tyk-dashboard
    environment:
      - TYK_DB_STORAGE_MAIN_TYPE=mongo
    ports:
      - "3000:3000"
    volumes:
      - ./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    networks:
      - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:v3.0.9
    container_name: tyk-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./confs/tyk.conf:/opt/tyk-gateway/tyk.conf
    networks:
      - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.6rc3
    container_name: tyk-pump
    volumes:
      - ./confs/pump.conf:/opt/tyk-pump/pump.conf
    networks:
      - tyk

  redis-node-5:
    image: docker.io/bitnami/redis-cluster:6.0
    ports:
      - "6380:6379"
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    networks:
      - tyk

  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - tyk

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - tyk

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - tyk

  redis-node-3:
    image: docker.io/bitnami/redis-cluster:6.0
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - tyk

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:6.0
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - tyk

  tyk-mongo:
    image: mongo:4.0
    container_name: tyk-mongo
    command: ["mongod", "--smallfiles"]
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - tyk

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
  db-data:

networks:
  tyk: